version: '3.8'

services:
  nemo-asr:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nemo-asr-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - MODEL_PATH=/app/models/stt_hi_conformer_ctc_medium.onnx
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=  # Set to GPU ID for GPU acceleration, empty for CPU only
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    
  # Optional: nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: nemo-asr-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nemo-asr
    profiles:
      - production
    restart: unless-stopped

volumes:
  models:
  logs:
